const multiDayTextBlocks = [
    {
        startMonth: 2,
        startDay: 13,
        startYear: 1945,
        endMonth: 2,
        endDay: 15,
        endYear: 1945,
        wikiUrl: 'https://en.wikipedia.org/wiki/Bombing_of_Dresden',
        text: 'DRESDEN',
        fontSize: '2.4em',
        fontFamily: 'Arial',
        bold: true,
        color: 'black',
        backgroundColor: 'orange',
        crop: { top: 30, right: 0, bottom: 10, left: 0 },
        position: { top: '40%', left: '12%' },
        scale: 1,
        height: 1,  // New simplified height property
        verticalOffset: 0,
        textWeek: [1],
        zIndexOverride: 20
      },
      {
        startMonth: 11,
        startDay: 30,
        startYear: 1939,
        endMonth: 3,
        endDay: 13,
        endYear: 1940,
        wikiUrl: 'https://en.wikipedia.org/wiki/Winter_War',
        text: 'THE WINTER WAR',
        fontSize: '2.3em',
        fontFamily: '',
        bold: true,
        color: 'black',
        backgroundColor: 'RED',
        crop: { top: 30, right: 0, bottom: 10, left: 0 },
        position: { top: '45%', left: '25%' },
        scale: 1,
        height: .8,  // New simplified height property
        verticalOffset: 1,
        textWeek: [3,8,13,18],
        zIndexOverride: 20
      },
      {
        startMonth: 3,
        startDay: 9,
        startYear: 1945,
        endMonth: 3,
        endDay: 10,
        endYear: 1945,
        wikiUrl: 'https://en.wikipedia.org/wiki/Bombing_of_Tokyo_(10_March_1945)',
        text: 'TOKYO',
        fontSize: '2.4em',
        fontFamily: 'Arial',
        bold: true,
        color: 'black',
        backgroundColor: 'orange',
        crop: { top: 30, right: 0, bottom: 10, left: 0 },
        position: { top: '40%', left: '10%' },
        scale: 1,
        height: 1,  // New simplified height property
        verticalOffset: 0,
        textWeek: [1],
        zIndexOverride: 21
      },
      {
        startMonth: 2,
        startDay: 4,
        startYear: 1945,
        endMonth: 2,
        endDay: 11,
        endYear: 1945,
        wikiUrl: 'https://en.wikipedia.org/wiki/Yalta_Conference',
        text: 'YALTA',
        fontSize: '4em',
        fontFamily: '',
        bold: true,
        color: 'black',
        backgroundColor: 'gold',
        crop: { top: 30, right: 0, bottom: 10, left: 0 },
        position: { top: '30%', left: '33%' }, // Adjust the text 10% down and 20% from the left
        scale: 1.,
        height: 1,  // New simplified height property
        verticalOffset: 0,
        textWeek: [1],
        zIndexOverride: 20
      },
      {
        startMonth: 7,
        startDay: 17,
        startYear: 1945,
        endMonth: 8,
        endDay: 2,
        endYear: 1945,
        wikiUrl: 'https://en.wikipedia.org/wiki/Potsdam_Conference',
        text: 'POTSDAM',
        fontSize: '4em',
        fontFamily: '',
        bold: true,
        color: 'black',
        backgroundColor: 'gold',
        crop: { top: 30, right: 0, bottom: 10, left: 0 },
        position: { top: '30%', left: '%' }, // Adjust the text 10% down and 20% from the left
        scale: 1.,
        height: 1,  // New simplified height property
        verticalOffset: 0,
        textWeek: [2],
        zIndexOverride: 20
      },
      {
        startMonth: 12,
        startDay: 16,
        startYear: 1944,
        endMonth: 1,
        endDay: 28,
        endYear: 1945,
        wikiUrl: 'https://en.wikipedia.org/wiki/Battle_of_the_Bulge',
        text: 'BATTLE OF THE BULGE',
        fontSize: '2.3em',
        fontFamily: '',
        bold: true,
        color: 'black',
        backgroundColor: 'LIGHTBLUE',
        crop: { top: 30, right: 0, bottom: 10, left: 0 },
        position: { top: '45%', left: '15%' },
        scale: 1,
        height: .8,  // New simplified height property
        verticalOffset: 1,
        textWeek: [3,5],
        zIndexOverride: 20
      },
      {
        startMonth: 4,
        startDay: 16,
        startYear: 1945,
        endMonth: 5,
        endDay: 2,
        endYear: 1945,
        wikiUrl: 'https://en.wikipedia.org/wiki/Battle_of_Berlin',
        text: 'BATTLE OF BERLIN',
        fontSize: '2.3em',
        fontFamily: '',
        bold: true,
        color: 'black',
        backgroundColor: 'RED',
        crop: { top: 30, right: 0, bottom: 10, left: 0 },
        position: { top: '45%', left: '25%' },
        scale: 1,
        height: .8,  // New simplified height property
        verticalOffset: 25,  // New property to adjust vertical position
        textWeek: [2],  // Keep textWeek as before
        zIndexOverride: 9  // Example zIndexOverride
      },
      {
        startMonth: 2,
        startDay: 19,
        startYear: 1945,
        endMonth: 3,
        endDay: 26,
        endYear: 1945,
        wikiUrl: 'https://en.wikipedia.org/wiki/Battle_of_Iwo_Jima',
        text: 'IWO JIMA',
        fontSize: '3em',
        fontFamily: '',
        bold: true,
        color: 'black',
        backgroundColor: 'lightblue',
        crop: { top: 30, right: 0, bottom: 10, left: 0 },
        position: { top: '30%', left: '30%' },
        scale: 1,
        height: .8,  // New simplified height property
        verticalOffset: 0,
        textWeek: [2,5],
        zIndexOverride: 20
      },
      {
        startMonth: 4,
        startDay: 1,
        startYear: 1945,
        endMonth: 6,
        endDay: 25,
        endYear: 1945,
        wikiUrl: 'https://en.wikipedia.org/wiki/Battle_of_Okinawa',
        text: 'OKINAWA',
        fontSize: '3em',
        fontFamily: '',
        bold: true,
        color: 'black',
        backgroundColor: 'lightblue',
        crop: { top: 30, right: 0, bottom: 10, left: 0 },
        position: { top: '30%', left: '30%' },
        scale: 1,
        height: .8,  // New simplified height property
        verticalOffset: 0,
        textWeek: [1,8,13],
        zIndexOverride: 8
      },
      {
        startMonth: 6,
        startDay: 26,
        startYear: 1945,
        endMonth: 7,
        endDay: 2,
        endYear: 1945,
        wikiUrl: 'https://www.roberthjackson.org/nuremberg-event/the-london-conference-june-26-august-2-1945/',
        text: 'LONDON CONFERENCE',
        fontSize: '2em',
        fontFamily: '',
        bold: true,
        color: 'black',
        backgroundColor: 'grey',
        crop: { top: 30, right: 0, bottom: 10, left: 0 },
        position: { top: '40%', left: '5%' },
        scale: 1,
        height: .8,  // New simplified height property
        verticalOffset: 0,
        textWeek: [1],
        zIndexOverride: 8
      },
      {
        startMonth: 5,
        startDay: 8,
        startYear: 1945,
        endMonth: 5,
        endDay: 8,
        endYear: 1945,
        wikiUrl: 'https://en.wikipedia.org/wiki/Victory_in_Europe_Day',
        text: 'VE',
        fontSize: '3.8em',
        fontFamily: '',
        bold: true,
        color: 'black',
        backgroundColor: 'white',
        crop: { top: 30, right: 0, bottom: 0, left: 0 },
        position: { top: '30%', left: '0%' },
        scale: 1,
        height: 1,  // New simplified height property
        verticalOffset: 0,
        textWeek: [1],
        zIndexOverride: 80
      },
  ];